version: '3.7'
services:
  emi:
    image: ahmetcancomtr1/xbot
    privileged: true
    tty: true
    restart: always
    shm_size: 32gb
    ports:
      - 0.0.0.0:25901:5901 
      - 0.0.0.0:26901:6901
    volumes:
      - ./volume/files:/files
      - ./xbot:/xbot
    environment: 
      - MEDIA_PATH=/files/
      - MONGO_CONN=mongodb://root:80190221@mongodb:25000/
      - WORKERID=1 
      - VNC_PW=emi


  mongodb:
    image: ahmetcancomtr1/mongo-b
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=80190221
      - AWS_ACCESS_KEY_ID=AKIA3CORLRRTVZVYBN47
      - AWS_SECRET_ACCESS_KEY=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
      - S3_URL=s3://xbot/database
      - S3B_INTERVAL=21600 #6saat 
      #- S3B_RESTORE=1 #restore at startup 
    restart: always
    ports:
      - 0.0.0.0:25000:27017
    volumes:
      - ./volume/database:/data/db
      - ./volume/backup:/backup
    #logging:
    #    driver: none 
  s3backup:
        image: ahmetcancomtr1/s3b
        restart: always
        volumes:
          - ./volume/files:/files
        environment: 
          - AWS_ACCESS_KEY_ID=AKIA3CORLRRTVZVYBN47
          - AWS_SECRET_ACCESS_KEY=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
          - S3B_SOURCES=/files
          - S3B_TARGETS=s3://xbot/files
          - S3B_INTERVAL=21600 #6saat 
          #- S3B_RESTORE=1 #restore at startup 
networks:
  default:
      name: xbot_network
    
