FROM accetto/ubuntu-vnc-xfce

ADD scripts/vnc_startup.sh /dockerstartup

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true

RUN apt update

RUN apt install -y build-essential software-properties-common wget git curl

RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt install wget openjdk-8-jdk python3.8 python3-pip ffmpeg -y 

RUN  rm /usr/bin/python;ln -s /usr/bin/python3.8 /usr/bin/python 
RUN  python -m pip install pymongo instaloader asyncio langdetect

RUN update-java-alternatives --set java-1.8.0-openjdk-amd64

# Install SDK Manager
# you can find this file at https://developer.android.com/studio/index.html#downloads - section command line only
RUN  wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip

ENV ANDROID_SDK_ROOT=/opt/androidsdk
ENV ANDROID_EMULATOR_HOME=$ANDROID_SDK_ROOT/.android
ENV ANDROID_AVD_HOME=$ANDROID_EMULATOR_HOME/avd

RUN mkdir -p $ANDROID_AVD_HOME

RUN apt install unzip -y && unzip sdk-tools-linux-4333796.zip -d $ANDROID_SDK_ROOT

RUN echo "export ANDROID_HOME=$ANDROID_SDK_ROOT" >> ~/.bashrc
RUN echo "export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> ~/.bashrc
RUN echo "export ANDROID_EMULATOR_HOME=$ANDROID_EMULATOR_HOME" >> ~/.bashrc
RUN echo "export ANDROID_AVD_HOME=$ANDROID_AVD_HOME" >> ~/.bashrc
RUN echo "export PATH=$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH" >> ~/.bashrc

# Install Android Image version 29
RUN yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager "platform-tools" "platforms;android-29" "emulator"
RUN yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager "system-images;android-29;default;x86_64"

RUN rm -r $ANDROID_SDK_ROOT/system-images/android-29/default/x86_64
ADD customimg/x86_64 $ANDROID_SDK_ROOT/system-images/android-29/default/x86_64

RUN  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install;rm -r aws
